### ISSUE TITLE
getting the error cannot synchronised guest cart 

### ISSUE THREAD

**Issue by anilahy** [DivanteLtd/magento2-external-checkout#6]
there is an issue when adding product as a guest user and completing the checkout form magento2
it works for the first time but repeating the same thing with gust user. it gives error:
 Cannot synchronize guest cart

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/magento2-external-checkout/pull/5/filesPlease check this fix
--

**Comment by anilahy** [comment]
@pkarw 
I get the latest pull of the module but still not resolved.

**Comment by pkarw** [comment]
Duplicate of #4 Closing this one
